apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Terraform_repo
  description: Azure AD user/group terraform IAC  repository
  tag:
    - terraform
    - azure AD
spec:
  type: service
  lifecycle: experimental
  owner: user:Jenny Doe
