apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: pipeline-2
  description: Jenkins Cogniassist discovery pipeline
  annotations:
    backstage.io/jenkins-only: 'true'
    jenkins.io/job-full-name: discovery-pipeline/discovery-pipeline
    backstage.io/kubernetes-namespace: cogniassist-discovery
    # jenkins.io/github-folder: 'https://github.com/VIVEK-cogniwide/Event-managment-system'
spec:
  type: service
  lifecycle: experimental
  owner: user:VIVEK-cogniwide
