apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Loom
  description: Cogniloom IDP portal
  annotations:
    backstage.io/kubernetes-id: kubernetes
    backstage.io/kubernetes-label-selector: 'app=backstage'
    backstage.io/kubernetes-namespace: loom
    # Second Kubernetes cluster
    # backstage.io/kubernetes-id-1: aks-production
    # backstage.io/kubernetes-label-selector-1: 'app.kubernetes.io/instance=cogniassist-backend'
    # backstage.io/kubernetes-namespace-1: cogniassist-backend-prod
    
    # # Third Kubernetes cluster (if needed)
    # backstage.io/kubernetes-id-2: aks-staging
    # backstage.io/kubernetes-label-selector-2: 'app.kubernetes.io/instance=cogniassist-backend'
    # backstage.io/kubernetes-namespace-2: cogniassist-backend-staging
spec:
  type: service
  lifecycle: experimental
  owner: user:VIVEK-cogniwide
  
