apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Cogniassist-discovery 
  description: Cogniassist discovery AKS cluster resources
  annotations:
    backstage.io/kubernetes-id: aks-pe-poc
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/app=bobbins'
    backstage.io/kubernetes-namespace: cogni-loom
   
spec:
  type: service
  lifecycle: experimental
  owner: user:VIVEK-cogniwide
  # kubernetes:
  #   cluster: minikube-local
  #   namespace: default
   
