apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Harbor
  description: Harbor Image Registry
  annotations:
    backstage.io/jenkins-only: 'true'
    backstage.io/kubernetes-id: aks-pe-poc
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/app=warp'
    backstage.io/kubernetes-namespace: warp
spec:
  type: service
  lifecycle: experimental
  owner: infra-team
 
  
