apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Mongodb
  description: Cogniassist AKS cluster resource
  annotations:
    backstage.io/kubernetes-id: aks-pe-poc
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=mongo'
    backstage.io/kubernetes-namespace: mongodb
spec:
  type: service
  lifecycle: experimental
  owner: user:VIVEK-cogniwide
  # kubernetes:
  #   cluster: minikube-local
  #   namespace: default
   
