apiVersion: backstage.io/v1alpha1
kind: dab_service
metadata:
  namespace: default
  name: dab-services
  description: Cogniassist Backend AKS cluster resources
  annotations:
    backstage.io/kubernetes-id: eks-microservices-dab-dev
    backstage.io/kubernetes-label-selector: "app.kubernetes.io/instance=dab-core-authentication"
    backstage.io/kubernetes-namespace: dab-core-microservices
spec:
  type: service
  lifecycle: Development
  owner: team-a
  system: cogniwide
