apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: harness
  description: Harness ci/cd component
  annotations:
    # harness.io/accountId: _cFLn0VGSK2xFNo3rUkiEg
    # harness.io/orgId: DABCO_CICD
    # harness.io/projectId: pairpointnonprod
    harness.io/pipelines: |
      MPGSPipeline: https://app.harness.io/ng/account/_cFLn0VGSK2xFNo3rUkiEg/home/orgs/DABCO_CICD/projects/pairpointnonprod/pipelines/cidabcorempgs/pipeline-studio/?repoName=devops-tooling%2Fpairpoint-harness-library&connectorRef=account.PPGITLABSA&storeType=REMOTE
      test2: https://app.harness.io/ng/account/_cFLn0VGSK2xFNo3rUkiEg/all/orgs/DABCO_CICD/projects/pairpointnonprod/pipelines/test2/executions?storeType=INLINE&searchTerm=&myDeployments=false&timeRange%5BtimeRangeFilterType%5D=LAST_YEAR
      keycloakConfig: https://app.harness.io/ng/account/_cFLn0VGSK2xFNo3rUkiEg/all/orgs/DABCO_CICD/projects/pairpointnonprod/pipelines/KeycloakConfig/pipeline-studio/?storeType=INLINE
  tags:
    - java

  links:
    - url: https://app.harness.io/user
      title: Examples Users
      icon: user
    - url: https://app.harness.io/group
      title: Example Group
      icon: group
    - url: https://app.harness.io/cloud
      title: Link with Cloud Icon
      icon: cloud
    - url: https://app.harness.io/dashboard
      title: Dashboard
      icon: dashboard
    - url: https://app.harness.io/help
      title: Support
      icon: help
    - url: https://app.harness.io/web
      title: Website
      icon: web
    - url: https://app.harness.io/alert
      title: Alerts
      icon: alert
spec:
  type: service
  lifecycle: experimental
  owner: team-a  # harness registering component in backstage
