apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: harness
  description: Harness ci/cd component
  annotations:
    # mandatory annotation
    harness.io/project-url: https://teams.microsoft.com/l/message/19:57ffa94d-7227-4dfb-b58d-0c7984b734fe_730db4af-81a8-43eb-b701-b8449d4bde9a@unq.gbl.spaces/1745990586659?context=%7B%22contextType%22%3A%22chat%22%7D
    # optional annotations, don't include this block if not needed. Add this if specific pipeline executions needs to be shown on the Plugin. When specified, latest pipeline execution details for configured pipelineIds(max 10) and configured serviceId will be shown.
    harness.io/ci-pipelineIds: test
    harness.io/cd-serviceId: <serviceId>
  tags:
    - java

  links:
    - url: https://app.harness.io/user
      title: Examples Users
      icon: user
    - url: https://app.harness.io/group
      title: Example Group
      icon: group
    - url: https://app.harness.io/cloud
      title: Link with Cloud Icon
      icon: cloud
    - url: https://app.harness.io/dashboard
      title: Dashboard
      icon: dashboard
    - url: https://app.harness.io/help
      title: Support
      icon: help
    - url: https://app.harness.io/web
      title: Website
      icon: web
    - url: https://app.harness.io/alert
      title: Alerts
      icon: alert
spec:
  type: service
  lifecycle: experimental
  owner: team-a
