apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Nginx
  description: Nginx Ingress Controller Cogniassist AKS cluster resource 
  annotations:
    backstage.io/kubernetes-id: aks-pe-poc
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=nginx'
    backstage.io/kubernetes-namespace: ingress-nginx
spec:
  type: service
  lifecycle: experimental
  owner: user:VIVEK-cogniwide
  # kubernetes:
  #   cluster: minikube-local
  #   namespace: default
  
